Vagrant.configure("2") do |config|
  
	config.vm.box = "generic/debian10"

	config.vm.define "mtellalS" do |guest|
		# SET MACHINE HOSTNAME
		guest.vm.hostname = "mtellalS"
		
		# SET MACHINE IP ADDR
		guest.vm.network "private_network", ip: "192.168.56.110"

		# SET SHARED FOLDER	
		guest.vm.synced_folder "./shared", "/home/vagrant/shared"
	
		# FORWARD PORTS
		config.vm.network "forwarded_port", guest: 80, host: 8080

		# PROVISION 
		guest.vm.provision "shell", path: "shared/server.sh"

		# DEFINE VM RESSOURCES
		guest.vm.provider "virtualbox" do |vm|
			vm.memory = 2048
			vm.cpus = 2
		end
	end

end
