Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    
    config.vm.define "antbarbiS" do |s|
        s.vm.hostname= "antbarbiS"
        s.vm.network "private_network", ip: "192.168.56.110"
        s.vm.synced_folder "shared", "/shared"
        s.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "2"
        end
        s.vm.provision "shell", path: "./scripts/s_script.sh"

    end

    config.vm.define "antbarbiSW" do |sw|
        sw.vm.hostname= "antbarbiSW"
        sw.vm.network "private_network", ip: "192.168.56.111"
        sw.vm.synced_folder "shared", "/shared"
        sw.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "2"
        end
        sw.vm.provision "shell", path: "./scripts/sw_script.sh"
    end
end