Vagrant.configure("2") do |config|
  
	config.vm.box = "generic/debian12"

	config.vm.define "mtellalS" do |guest|

		# SET MACHINEN HOSTNAME
		guest.vm.hostname = "mtellalS"

		# SET MACHINE IP ADDR
		guest.vm.network "private_network", ip: "192.168.56.110"

		# SET SHARED FOLDER
		guest.vm.synced_folder "./", "/home/vagrant/shared"
				
		# PROVISION
		guest.vm.provision "shell", path: "scripts/server.sh"

			# DEFINE MACHINE RESSOURCES
			guest.vm.provider "virtualbox" do |vm|
					vm.memory = 512
					vm.cpus = 1
			end
	end

	config.vm.define "mtellalSW" do |guest|
		
		# SET MACHINE HOSTNAME
		guest.vm.hostname = "mtellalSW"
		
		# SET MACHINE IP ADDR
		guest.vm.network "private_network", ip: "192.168.56.111"

		# SET SHARED FOLDER	
		guest.vm.synced_folder "./", "/home/vagrant/shared"
	
		# PROVISION 
		guest.vm.provision "shell", path: "scripts/server_worker.sh"

		# DEFINE VM RESSOURCES
		guest.vm.provider "virtualbox" do |vm|
			vm.memory = 512
			vm.cpus = 1
		end
	end

end
