Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    
    config.vm.define "antbarbiS" do |s|
        s.vm.hostname= "antbarbiS"
        s.vm.network "private_network", ip: "192.168.56.110"
        s.vm.synced_folder "shared", "/shared"
        s.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "2"
        end
        s.vm.provision "shell", path: "./scripts/s_script.sh"
    end
end